import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../app/ui/globals.css";

const geist = Geist({
  subsets: ['latin'],
})


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "MyDeporte",
  description: "Generated by create next app",
     // Incluye tu etiqueta de verificación aquí
  other: {
      'google-site-verification': 'google9ba9e0c49226ea45.html'
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={geist.className}>
    
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
